name: Publish package to GitHub Packages

on:
    release:
        types: [published]

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            # 1️⃣ Checkout repository
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2️⃣ Setup Node.js with GitHub Packages registry
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@tfpkgr'

            # 3️⃣ Cache Node.js modules
            - name: Cache Node.js modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # 4️⃣ Configure npm for installing dependencies
            - name: Configure npm for installing public GitHub Packages
              run: |
                  echo "@tfpkgr:registry=https://npm.pkg.github.com" > ~/.npmrc
                  echo "always-auth=true" >> ~/.npmrc
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

            # 5️⃣ Install dependencies
            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # 6️⃣ Build the package
            - name: Build the package
              run: npm run build

            # 7️⃣ Define the exports field in package.json (if applicable)
            - name: Define the exports field in package.json
              run: npm run define-exports

            # 8️⃣ Bump version from release tag
            - name: Bump package version
              uses: technote-space/package-version-check-action@v1

            # 9️⃣ Publish to GitHub Packages (public)
            - name: Publish package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
